In [ ]:
from matplotlib.colors import LogNorm


def plot_graphs(filename: Path):
    res = pd.read_csv(filename)

    y_true = res.y_true
    y_pred = res.y_pred.clip(upper=1)
    y_af2 = res.y_pred_af2

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

    n_bins = 175
    cmap = ["magma", "plasma", "inferno", "cubehelix"][2]
    norm = LogNorm()

    h1 = ax1.hexbin(y_true, y_af2, gridsize=n_bins, cmap=cmap, norm=norm)
    fig.colorbar(h1, ax=ax1)
    ax1.set_xlabel("True LDDT")
    ax1.set_ylabel("AF2 pLDDT")
    ax1.set_title("True vs AF2 pLDDT")
    ax1.set_xlim(left=0)
    ax1.set_ylim(bottom=0)
    ax1.grid(True, alpha=0.2)

    h2 = ax2.hexbin(y_true, y_pred, gridsize=n_bins, cmap=cmap, norm=norm)
    fig.colorbar(h2, ax=ax2)
    ax2.set_xlabel("True LDDT")
    ax2.set_ylabel("Model Predicted LDDT")
    ax2.set_title("True vs Model Prediction")
    ax2.set_xlim(left=0)
    ax2.set_ylim(bottom=0)
    ax2.grid(True, alpha=0.2)

    fig.tight_layout()
    plt.show()


file = Path("/home/fahim/compbio/out/rf-5s-exclusive/fold_0/predict.csv")
plot_graphs(file)

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

from trainer import make_feature_matrix

# df = pd.read_csv("/home/fahim/compbio/data/all_data_flags_max_with_repeat_all_update.csv")
# df = pd.read_csv("data/all_data_flags_max_with_repeat_all_update.csv")
model_cls = (RandomForestRegressor,)
model_init_params = {
    "n_estimators": 128,
    "max_depth": None,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": None,
    "bootstrap": True,
    "random_state": 42,
    "n_jobs": -1,
    "verbose": 0,
}
categ_cols = [
    "residue",
    "nbr_s1",
    "nbr_s2",
    "nbr_s3",
    # "nbr_s4",
    # "nbr_s5",
    "nbr_sasa_s1",
    "nbr_sasa_s2",
    "nbr_sasa_s3",
    # "nbr_sasa_s4",
    # "nbr_sasa_s5",
    "nbr_depth_s1",
    "nbr_depth_s2",
    "nbr_depth_s3",
    # "nbr_depth_s4",
    # "nbr_depth_s5",
    "af2_max_flag",
]
numer_cols = [
    "af2_sd",
    "af2_max_ss%",
    "af2_flag_repeat_len",
    "plddt",
]

df = pd.read_json("data/feature_5se_sasa_rd_df.json")
df
# train_df, test_df = train_test_split(df, train_size=0.75, random_state=42, stratify=df["af2_pdb"])
# X_train, y_train, y_af2_train = make_feature_matrix(train_df, categ_cols, numer_cols)
# X_test, y_test, y_af2_test = make_feature_matrix(test_df, categ_cols, numer_cols)

# model = model_cls(**model_init_params)
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)
# y_pred = np.clip(y_pred, 0, 1)

# test_df["pred"] = y_pred
# test_df["ss_mismatch"] = int(row["af2_max_flag"] != row["nmr_max_flag"])

,af2_pdb,res_num,res_name,residue,nbr_s1,nbr_s2,nbr_s3,nbr_s4,nbr_s5,nbr_sasa_s1,...,af2_sd,af2_max_ss%,af2_max_flag,af2_flag_repeat_len,plddt,nmr_sd,nmr_max_ss%,nmr_max_flag,nmr_flag_repeat_len,lddt
0,1B75_af2_model1.pdb,1,MET,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 1, 0, 0, 0, 0, ...","[4, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 0, ...","[None, None, None, None, None, None, None, Non...",...,0.0280,1.00,"[0.0, 0.0, 1.0]",2,0.7469,0.0942,1.00,"[0.0, 0.0, 1.0]",2,0.7381
1,1B75_af2_model1.pdb,2,PHE,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ...","[0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, ...","[2, 0, 0, 1, 0, 0, 0, 1, 4, 0, 0, 2, 0, 1, 0, ...","[3, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, ...","[None, None, None, None, None, None, None, Non...",...,0.0119,0.76,"[0.0, 0.0, 1.0]",2,0.8991,0.0440,0.50,"[0.0, 0.0, 1.0]",2,0.8016
2,1B75_af2_model1.pdb,3,THR,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...","[1, 0, 0, 2, 1, 0, 0, 1, 4, 1, 1, 0, 0, 1, 0, ...","[4, 0, 3, 3, 1, 1, 1, 3, 1, 0, 1, 1, 0, 0, 1, ...","[None, None, None, None, None, None, None, Non...",...,0.0078,1.00,"[0.0, 1.0, 0.0]",6,0.9368,0.0279,0.80,"[0.0, 1.0, 0.0]",6,0.8598
3,1B75_af2_model1.pdb,4,ILE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, ...","[1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, ...","[2, 0, 2, 3, 2, 1, 1, 2, 3, 0, 3, 1, 0, 1, 0, ...","[2, 0, 1, 2, 1, 0, 1, 3, 2, 2, 0, 0, 1, 0, 1, ...","[None, None, None, None, None, None, None, Non...",...,0.0066,1.00,"[0.0, 1.0, 0.0]",6,0.9445,0.0257,1.00,"[0.0, 1.0, 0.0]",6,0.8634
4,1B75_af2_model1.pdb,5,ASN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...","[1, 0, 1, 2, 1, 1, 1, 2, 2, 1, 0, 0, 0, 0, 0, ...","[2, 0, 0, 0, 3, 0, 0, 3, 2, 1, 3, 2, 1, 1, 1, ...","[None, None, None, None, None, None, None, Non...",...,0.0062,1.00,"[0.0, 1.0, 0.0]",6,0.9526,0.0448,1.00,"[0.0, 1.0, 0.0]",6,0.7764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482932,9VG5_af2_model1.pdb,112,GLY,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, ...","[0, 0, 1, 1, 1, 1, 0, 0, 0, 3, 0, 0, 0, 1, 1, ...","[None, None, None, None, None, None, None, Non...",...,0.0462,0.56,"[0.0, 0.0, 1.0]",4,0.5886,0.0807,0.90,"[0.0, 0.0, 1.0]",7,0.7851
482933,9VG5_af2_model1.pdb,113,PHE,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, ...","[None, None, None, None, None, None, None, Non...",...,0.0451,0.84,"[0.0, 0.0, 1.0]",4,0.5476,0.0964,0.95,"[0.0, 0.0, 1.0]",7,0.6531
482934,9VG5_af2_model1.pdb,114,GLY,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, ...","[None, None, None, None, None, None, None, Non...",...,0.0284,0.84,"[0.0, 0.0, 1.0]",4,0.4675,0.1117,0.95,"[0.0, 0.0, 1.0]",7,0.6298
482935,9VG5_af2_model1.pdb,115,MET,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, None, None, None, None, None, Non...",...,0.0405,0.56,"[0.0, 0.0, 1.0]",4,0.3650,0.1179,1.00,"[0.0, 0.0, 1.0]",7,0.4771
482936,9VG5_af2_model1.pdb,116,LEU,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, None, None, None, None, None, Non...",...,0.0255,1.00,"[0.0, 0.0, 1.0]",1,0.3753,0.1316,1.00,"[0.0, 0.0, 1.0]",7,0.3788

In [1]:
import numpy as np

np.array([1, 2, 3]) / np.array([1, 0, 3])

/tmp/ipykernel_1751130/1020231108.py:3: RuntimeWarning: divide by zero encountered in divide
  np.array([1, 2, 3]) / np.array([1, 0, 3])

array([ 1., inf,  1.])

In [ ]:
## MLP with 128, 256, 128
# metrics_with_sd = {
#     "MAE": 0.07773271581964343,
#     "RMSE": 0.10188284933411089,
#     "R^2": 0.5118117622235373,
#     "AF2_MAE": 0.09744499730815422,
#     "AF2_RMSE": 0.13332470855263298,
#     "AF2_R^2": 0.16399970072599912,
# }

# metrics_no_sd = {
#     "MAE": 0.07702314559210688,
#     "RMSE": 0.10209183279145384,
#     "R^2": 0.5098069517540054,
#     "AF2_MAE": 0.09744499730815422,
#     "AF2_RMSE": 0.13332470855263298,
#     "AF2_R^2": 0.16399970072599912,
# }

## MLP with 128, 128
# metrics_with_sd = {
#     "MAE": 0.07954207706894438,
#     "RMSE": 0.10298651057246853,
#     "R^2": 0.5011777306011409,
#     "AF2_MAE": 0.09744499730815422,
#     "AF2_RMSE": 0.13332470855263298,
#     "AF2_R^2": 0.16399970072599912,
# }

# metrics_no_sd = {
#     "MAE": 0.0789922855034896,
#     "RMSE": 0.10261853457182603,
#     "R^2": 0.5047359965864326,
#     "AF2_MAE": 0.09744499730815422,
#     "AF2_RMSE": 0.13332470855263298,
#     "AF2_R^2": 0.16399970072599912,
# }

# metrics_no_sd_by_prot = {
#     "MAE": 0.07787989602760159,
#     "RMSE": 0.10203089001377119,
#     "R^2": 0.5040390141424378,
#     "AF2_MAE": 0.09743999494677037,
#     "AF2_RMSE": 0.13232380356290427,
#     "AF2_R^2": 0.16581934070236715,
# }

In [ ]:
df = pd.read_json("data/feature_df.json")
df

,neighbor_3,neighbor_6,neighbor_10,residue,af2_pdb,af2_sd,af2_max_ss%,af2_max_flag,af2_flag_repeat_len,plddt,lddt
0,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1B75_af2_model1.pdb,0.0280,1.00,C,2,0.7469,0.7381
1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, ...","[0, 0, 0, 2, 2, 0, 0, 3, 3, 1, 2, 2, 0, 1, 0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1B75_af2_model1.pdb,0.0119,0.76,C,2,0.8991,0.8016
2,"[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 2, 1, 0, 0, 0, ...","[1, 0, 0, 1, 3, 0, 0, 3, 3, 2, 2, 1, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1B75_af2_model1.pdb,0.0078,1.00,E,6,0.9368,0.8598
3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...","[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, ...","[1, 0, 2, 3, 4, 0, 0, 4, 2, 2, 3, 1, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",1B75_af2_model1.pdb,0.0066,1.00,E,6,0.9445,0.8634
4,"[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, ...","[1, 0, 2, 3, 2, 1, 0, 5, 2, 1, 1, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1B75_af2_model1.pdb,0.0062,1.00,E,6,0.9526,0.7764
...,...,...,...,...,...,...,...,...,...,...,...
482932,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, ...","[2, 0, 0, 0, 1, 1, 0, 1, 2, 2, 1, 0, 0, 1, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",9VG5_af2_model1.pdb,0.0462,0.56,T,4,0.5886,0.7851
482933,"[0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, ...","[2, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",9VG5_af2_model1.pdb,0.0451,0.84,T,4,0.5476,0.6531
482934,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",9VG5_af2_model1.pdb,0.0284,0.84,T,4,0.4675,0.6298
482935,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9VG5_af2_model1.pdb,0.0405,0.56,T,4,0.3650,0.4771
482936,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9VG5_af2_model1.pdb,0.0255,1.00,C,1,0.3753,0.3788